server:
  # 뭔가 큰 의미는 없음. 그냥 5000번 한거임
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: wanted
    password: wanted
  jpa:
    generate-ddl: false
    show-sql: true

